NAME	=	braiiiiiiinnnzzzz
SRC		=	main.cpp Zombie.cpp newZombie.cpp randomChump.cpp
OBJ		=	braiiiiiiinnnzzzz.o

all		:	$(NAME)
$(NAME) : $(SRC)
		clang++  -Wall -Wextra -Werror  $(SRC) -o $(NAME)
clean	:
		rm -f $(NAME)
fclean	: clean	
re		: fclean
		make all